# Generated by Django 2.2.10 on 2020-02-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ISBN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('publication_date', models.DateField()),
                ('num_of_pages', models.IntegerField()),
                ('link_to_cover', models.URLField(blank=True)),
                ('publication_lang', models.CharField(max_length=32)),
                ('author', models.ManyToManyField(to='books.Author')),
                ('isbn', models.ManyToManyField(to='books.ISBN')),
            ],
        ),
    ]
