# Generated by Django 2.2.10 on 2020-03-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_lang',
            field=models.CharField(max_length=32, verbose_name='publication language'),
        ),
        migrations.AlterField(
            model_name='isbn',
            name='number',
            field=models.CharField(max_length=32),
        ),
    ]
